# Generated by Django 4.0.3 on 2022-03-25 06:31

from django.db import migrations, models
import projects.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(help_text='Please enter a short summary for the project.', max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Production'), ('D', 'Development'), ('X', 'Abandoned'), ('R', 'Research')], default='R', max_length=1)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project_start_date', models.DateField(auto_now_add=True)),
                ('project_end_date', models.DateField(blank=True)),
                ('bg_image', models.ImageField(upload_to=projects.models.project_directory_path)),
                ('external_url', models.URLField()),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
