# Generated by Django 4.0.3 on 2022-03-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_url',
            field=models.URLField(null=True),
        ),
    ]
