# Generated by Django 4.0.3 on 2022-03-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_start_date',
            field=models.DateField(),
        ),
    ]
